name: Gettex Export

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:

      - name: Repository laden
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Pakete installieren
        run: pip install -r requirements.txt

      - name: Export starten
        run: python gettex_export.py

      - name: Excel hochladen
        uses: actions/upload-artifact@v4
        with:
          name: gettex-export
          path: "*.xlsx"
